#lang sicp

(define (make-frame origin edge1 edge2)
  (list origin edge1 edge2))
(define (origin-frame frame)
  (car frame))
(define (edge1-frame frame)
  (list-ref frame 1))
(define (edge2-frame frame)
  (list-ref frame 2))

(define (make-frame2 origin edge1 edge2)
  (cons origin (cons edge1 edge2)))
(define (origin-frame2 frame)
  (car frame))
(define (edge1-frame2 frame)
  (cadr frame))  ;; same as (car (cdr frame))
(define (edge2-frame2 frame)
  (caddr frame)) ;; same as (car (cdr (cdr frame)))

(define f (make-frame 1 2 3))
(display (origin-frame f))
(newline)
(display (edge1-frame f))
(newline)
(display (edge2-frame f))
(newline)
(display (origin-frame2 f))
(newline)
(display (edge1-frame2 f))
(newline)
(display (edge2-frame2 f))
(newline)
